

services:
  redis:
    image: redis:8.2.2
    container_name: conexao-redis
    hostname: conexao-redis
    restart: unless-stopped
    command: >
      sh -c 'redis-server
      --requirepass "${REDIS_PASSWORD?A senha do Redis não foi definida na variável REDIS_PASSWORD}"
      --appendonly yes
      --bind 0.0.0.0
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1000'
    ports:
      - "6379:6379"  # Expor para outros microsserviços
    networks:
      - conexao-network
      - conexao-network-swarm
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      org.opencontainers.image.title: "Conexão de Sorte Redis"
      org.opencontainers.image.description: "Redis Cache para microserviços"
      org.opencontainers.image.vendor: "Conexão de Sorte"
      org.opencontainers.image.version: "8.2.2"
      conexao.service.name: "redis"
      conexao.service.type: "infrastructure"

volumes:
  redis-data:
    driver: local

networks:
  conexao-network:
    name: conexao-network
    external: true
  # Compatibilidade com projetos que usam conexao-network-swarm
  conexao-network-swarm:
    name: conexao-network-swarm
    external: true
