version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: conexao-redis
    hostname: conexao-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD?A senha do Redis não foi definida na variável REDIS_PASSWORD} --appendonly yes
    ports:
      # - "6379:6379" # Descomente apenas para diagnóstico temporário e com firewall
    networks:
      - conexao-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis-data:
    driver: local

networks:
  conexao-network:
    name: conexao-network
    external: true
