---
# ============================================================================
# 🔴 CONEXÃO DE SORTE - REDIS INFRAESTRUTURA
# ============================================================================
# Data de Criação: 17/09/2025
# Última Atualização: 17/09/2025
# Responsável: Sistema Automatizado
# Versão: 2.0.0
# ============================================================================
#
# REDIS CACHE - Infraestrutura de Cache Distribuído
# - Docker Swarm deployment
# - Overlay encrypted network para segurança
# - Named volumes externos para persistência
# - Health checks otimizados para produção
# - Secrets externos gerenciados pelo Swarm
# ============================================================================

services:
  # ============================================================================
  # 🔴 REDIS CACHE - Cache Distribuído
  # ============================================================================
  redis:
    image: redis:8.2.1-alpine
    hostname: conexao-redis
    command: >
      sh -c '
      REDIS_PASS="$$(cat /run/secrets/conexao-de-sorte-redis-password)";
      if [ -z "$$REDIS_PASS" ]; then
        echo "FATAL: Redis password secret not available - refusing to start with insecure defaults";
        exit 1;
      fi;
      echo "Starting Redis with enhanced security configuration...";
      redis-server --requirepass "$$REDIS_PASS" --bind 0.0.0.0 --protected-mode yes --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
      '
    networks:
      conexao-network-swarm:
        aliases:
          - conexao-redis
          - redis
    volumes:
      - redis_data:/data
    secrets:
      - conexao-de-sorte-redis-password
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "$$(cat /run/secrets/conexao-de-sorte-redis-password)", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 30s
        max_failure_ratio: 0
    labels:
      org.opencontainers.image.title: "Conexão de Sorte Redis"
      org.opencontainers.image.description: "Redis Cache para microserviços"
      org.opencontainers.image.vendor: "Conexão de Sorte"
      org.opencontainers.image.version: "8.2.2-alpine"
      conexao.service.name: "redis"
      conexao.service.type: "infrastructure"
      conexao.service.environment: "production"

# ============================================================================
# 🔐 SECRETS EXTERNOS (Gerenciados pelo Docker Swarm)
# ============================================================================
secrets:
  conexao-de-sorte-redis-password:
    external: true
    name: conexao-de-sorte-redis-password

# ============================================================================
# 📦 VOLUMES EXTERNOS
# ============================================================================
volumes:
  redis_data:
    external: true
    name: redis_data

# ============================================================================
# 🌐 NETWORKS EXTERNOS
# ============================================================================
networks:
  conexao-network-swarm:
    external: true
    name: conexao-network-swarm
