name: "🔴 Redis Infrastructure - CI/CD Pipeline (Novo)"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVICE_NAME: redis-infrastructure

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    outputs:
      has_keyvault: ${{ steps.check_secrets.outputs.has_keyvault }}
      has_azure_creds: ${{ steps.check_secrets.outputs.has_azure_creds }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-yaml jq

      - name: Validate Docker Compose
        run: |
          docker compose -f docker-compose.yml config -q
          echo "✅ Docker Compose syntax is valid"

      - name: Security Validation - No Hardcoded Passwords
        run: |
          # Verificar se não há hardcoded passwords (excluindo secret names)
          if grep -r "password.*:" docker-compose.yml | grep -v "\${" | grep -v "#" | grep -v "external:" | grep -v "secrets:" | grep -v "conexao-de-sorte-.*-password:"; then
            echo "❌ Found potential hardcoded passwords"
            exit 1
          else
            echo "✅ No hardcoded passwords found"
          fi

      - name: 🔎 Validar OIDC Azure
        id: check_secrets
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}
          AZURE_KEYVAULT_ENDPOINT: ${{ secrets.AZURE_KEYVAULT_ENDPOINT }}
        run: |
          set -Eeuo pipefail
          missing=()
          for var in AZURE_CLIENT_ID AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID; do
            if [[ -z "${!var:-}" ]]; then
              missing+=("$var")
            fi
          done
          if (( ${#missing[@]} )); then
            printf '❌ GitHub Secrets obrigatórios ausentes: %s\n' "${missing[*]}"
            exit 1
          fi
          echo "✅ Identificadores Azure configurados via secrets"

          # Key Vault é opcional
          if [[ -n "${AZURE_KEYVAULT_NAME:-}" ]]; then
            echo "has_keyvault=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_keyvault=false" >> "$GITHUB_OUTPUT"
          fi

          if [[ -z "${AZURE_KEYVAULT_ENDPOINT:-}" ]]; then
            echo 'ℹ️ AZURE_KEYVAULT_ENDPOINT não definido (usando endpoint padrão)'
          else
            echo '✅ Endpoint customizado definido'
          fi

          echo "has_azure_creds=true" >> "$GITHUB_OUTPUT"

      - name: Validate YAML files
        run: |
          python3 -c "
          import yaml
          import pathlib

          # Validar arquivos YAML principais
          yaml_files = [
              'docker-compose.yml'
          ]

          for file_path in yaml_files:
              if pathlib.Path(file_path).exists():
                  try:
                      with open(file_path, 'r', encoding='utf-8') as f:
                          yaml.safe_load(f)
                      print(f'✅ YAML válido: {file_path}')
                  except Exception as e:
                      print(f'❌ Erro no YAML {file_path}: {e}')
                      exit(1)
          "

      - name: ✅ Confirmar consumo mínimo do Key Vault
        if: ${{ steps.check_secrets.outputs.has_keyvault == 'true' }}
        run: |
          echo 'Job de validação não consome segredos do Key Vault (lista vazia).'
          echo "✅ Validação de Key Vault concluída sem consumo de segredos"

      - name: Validation completed
        run: |
          echo "✅ Validação concluída - pronto para deploy"


  deploy-selfhosted:
    needs: validate-and-build
    runs-on: [self-hosted, Linux, X64, conexao-de-sorte-redis-infraestrutura]
    timeout-minutes: 15
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          clean: true
          fetch-depth: 1

      - name: 🔐 Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Key Vault secrets (Redis)
        if: ${{ needs.validate-and-build.outputs.has_keyvault == 'true' }}
        run: |
          # Usar endpoint se disponível, senão usar nome com fallback
          KEYVAULT_ENDPOINT="${{ secrets.AZURE_KEYVAULT_ENDPOINT }}"
          if [[ -n "$KEYVAULT_ENDPOINT" ]]; then
            KEYVAULT_NAME=$(echo "$KEYVAULT_ENDPOINT" | sed 's|https://\(.*\)\.vault\.azure\.net/.*|\1|')
            echo "📍 Usando Key Vault do endpoint: $KEYVAULT_NAME"
          else
            KEYVAULT_NAME="${{ secrets.AZURE_KEYVAULT_NAME || 'kv-conexao-de-sorte' }}"
            echo "📍 Usando Key Vault do nome: $KEYVAULT_NAME"
          fi

          # Obter secrets do Redis
          secrets_list="conexao-de-sorte-redis-password"

          IFS=',' read -ra SECRETS_ARRAY <<< "$secrets_list"
          for secret_name in "${SECRETS_ARRAY[@]}"; do
            echo "🔍 Obtendo segredo: $secret_name"
            secret_value=$(az keyvault secret show --vault-name "$KEYVAULT_NAME" --name "$secret_name" --query 'value' -o tsv 2>/dev/null || echo "")

            if [[ -n "$secret_value" ]]; then
              echo "✅ Segredo obtido: $secret_name"
              echo "$secret_name=$secret_value" >> $GITHUB_ENV
            else
              echo "❌ Erro ao obter segredo: $secret_name"
              exit 1
            fi
          done

      - name: Preparar secrets do Redis
        if: ${{ needs.validate-and-build.outputs.has_keyvault == 'true' }}
        run: |
          set -Eeuo pipefail
          password="${conexao-de-sorte-redis-password}"
          if [[ -z "$password" ]]; then
            echo '❌ Segredo do Redis não retornado pelo Key Vault'
            exit 1
          fi
          echo "::add-mask::$password"
          if [[ ${#password} -lt 12 ]]; then
            echo '❌ Password muito curto (mínimo 12 caracteres)'
            exit 1
          fi
          password_file="$RUNNER_TEMP/redis_password"
          printf '%s\n' "$password" > "$password_file"
          chmod 600 "$password_file"

      - name: Deploy Redis Infrastructure
        run: |
          set -Eeuo pipefail
          echo "🚀 Iniciando deploy da infraestrutura Redis..."

          STACK_NAME="conexao-redis"
          NETWORK_NAME="conexao-network-swarm"
          SECRET_NAME="conexao-de-sorte-redis-password"

          # Verificar se rede existe
          if ! docker network ls --format '{{.Name}}' | grep -Fxq "$NETWORK_NAME"; then
            echo "📡 Criando rede overlay $NETWORK_NAME..."
            docker network create --driver overlay --attachable "$NETWORK_NAME"
          else
            echo "✅ Rede $NETWORK_NAME já existe"
          fi

          # Verificar e criar volume se necessário
          if ! docker volume ls --format '{{.Name}}' | grep -Fxq "redis_data"; then
            echo "💾 Criando volume redis_data..."
            docker volume create redis_data
          else
            echo "✅ Volume redis_data já existe"
          fi

          # Gerenciar secret
          if [[ "${{ needs.validate-and-build.outputs.has_keyvault }}" == "true" ]]; then
            password_file="$RUNNER_TEMP/redis_password"

            # Verificar se secret existe
            if docker secret ls --format '{{.Name}}' | grep -Fxq "$SECRET_NAME"; then
              echo "ℹ️ Secret $SECRET_NAME já existe - utilizando existente"
            else
              echo "🔑 Criando secret $SECRET_NAME..."
              docker secret create "$SECRET_NAME" "$password_file"
            fi
          else
            echo "⚠️ Key Vault não configurado - usando secret existente"
            if ! docker secret ls --format '{{.Name}}' | grep -Fxq "$SECRET_NAME"; then
              echo "❌ Secret $SECRET_NAME não encontrado e Key Vault não configurado"
              exit 1
            fi
          fi

          # Remove stack existente se houver
          if docker stack ls --format '{{.Name}}' | grep -Fxq "$STACK_NAME"; then
            echo "🔄 Removendo stack existente $STACK_NAME..."
            docker stack rm "$STACK_NAME"

            # Aguardar remoção
            echo "⏳ Aguardando remoção da stack..."
            for i in $(seq 1 30); do
              if ! docker stack ls --format '{{.Name}}' | grep -Fxq "$STACK_NAME"; then
                break
              fi
              sleep 2
            done
          fi

          # Deploy da nova stack
          echo "🛠️ Fazendo deploy da stack $STACK_NAME..."
          docker stack deploy -c docker-compose.yml "$STACK_NAME"

          echo "✅ Deploy concluído!"

      - name: Health Check Redis (Non-blocking)
        run: |
          echo "🏥 Verificando saúde do Redis..."
          STACK_NAME="conexao-redis"

          # Aguardar serviços ficarem disponíveis (máximo 2 minutos)
          timeout=120
          elapsed=0

          while [ $elapsed -lt $timeout ]; do
            # Verificar status dos serviços
            service_count=$(docker service ls --filter name="${STACK_NAME}_" --format '{{.Name}}' | wc -l)

            if [ $service_count -gt 0 ]; then
              echo "✅ Serviços Redis encontrados"
              docker service ls --filter name="${STACK_NAME}_" --format "table {{.Name}}\t{{.Replicas}}\t{{.Image}}"

              # Verificar se há containers rodando
              running_tasks=$(docker service ps "${STACK_NAME}_redis" --filter desired-state=running --format '{{.Name}}' 2>/dev/null | wc -l)

              if [ $running_tasks -gt 0 ]; then
                echo "✅ Redis está sendo executado"
                break
              fi
            fi

            echo "⏳ Aguardando Redis ficar disponível... ($elapsed/$timeout segundos)"
            sleep 10
            elapsed=$((elapsed + 10))
          done

          # Status final (não bloqueante)
          echo "📊 Status final dos serviços Redis:"
          docker service ls --filter name="${STACK_NAME}_" --format "table {{.Name}}\t{{.Replicas}}\t{{.Image}}" || true

          echo "📋 Tarefas do Redis:"
          docker service ps "${STACK_NAME}_redis" --no-trunc --format "table {{.Name}}\t{{.CurrentState}}\t{{.Error}}" || true

          echo "ℹ️ Health check concluído (informativo apenas - não bloqueia pipeline)"