name: runner-smoke
on:
  workflow_dispatch:
jobs:
  smoke:
    runs-on: [self-hosted, Linux, X64, srv649924, conexao, conexao-de-sorte-redis-infraestrutura]
    steps:
      - name: Print runner host
        run: |
          echo "Host: $(hostname)"
          uname -a
      - name: Check GitHub API
        run: curl -s https://api.github.com/rate_limit | head -n 5
